---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        # https://bjw-s.github.io/helm-charts/docs/app-template/
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      uptime-kuma:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.15
            env:
              TZ: "${TIMEZONE}"

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 5m
                memory: 470M
              limits:
                memory: 470M

    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 568
    #     runAsGroup: 568
    #     fsGroup: 568
    #     fsGroupChangePolicy: OnRootMismatch
    #     supplementalGroups: [1026, 100] # 1026 - NFS Owner / 100 - NFS Group
    #     seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: uptime-kuma
        ports:
          http:
            port: &port 3001

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "uptime-kuma.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        enabled: true
        existingClaim: uptime-kuma
        globalMounts:
          - path: /app/data