---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 6.0.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    image:
      repository: nextcloud
      tag: 30.0.0-fpm-alpine
      flavor: fpm-alpine
    ingress:
      enabled: true
      className: nginx
      tls:
        - hosts:
            - &host nextcloud.${SECRET_DOMAIN_0}
          secretName: ${SECRET_DOMAIN_0//./-}-prod-tls
    nextcloud:
      host: *host
      datadir: /var/www/data
    nginx:
      enabled: true
      image:
        repository: nginx
        tag: 1.27-alpine
    internalDatabase:
      enabled: true
    externalDatabase:
      enabled: false
    cronjob:
      enabled: false
    resources:
      requests:
        cpu: 34m
        memory: 204Mi
      limits:
        memory: 363Mi