apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: media
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
        claimName: calibre
  containers:
  - name: busybox
    image: busybox:1.36
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: data
      mountPath: /data
    securityContext:
      allowPrivilegeEscalation: true
