apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:H6D5mCL0n5ZlewFxagDLT3N+JS+iCZ6wl5Bd5ztE8BAlTAFD,iv:iXTN05nZg7SoMoUW/1XBNfrjqR3dH4d+EPswj8e150o=,tag:ejP5YM2d9mGim2qqMt9IFw==,type:str]
    credentials.json: ENC[AES256_GCM,data:Up4/n3eSGsxe+tdQ0JKmbBeeFJOH/hTos1Ct2skWlfDFcaxJkCVmNMlFdCKUwj4Gle0lyG3+XpBgAX08fn3s40pipjpVfAyo6DmGFyzp/IayRi90kPfqpOnEdU3hgcKh0JaCZtP7OIJT5HZYNaWvbFNgpxxVfk5cMbzCN0dnLdF6LVjzcInXpyHi61zuPcCAn1IfrGZi1oE0Dq21oZRWDMP2Rf/z8uxCVHedhHHBjA==,iv:+bMiRwvhUA2iARTfxMjBcKCmq6b2hQAeTAyB3BRbilU=,tag:rhw/HORk8ZCnkese2ScyoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPakdXU3AxUURaOTFscVoz
            SnoyWDBjSTZacXJZbjBpeFgvSGJuYURqL1dnCk9YUWZZcjdjd3BPQWlPSTNqZXN3
            cEVWMWd4ZEtJR1hab3hqOGlGZExyM1kKLS0tIHZselVFOWtUcU5zMGJkV3B2dkVS
            aXZZNnVveG1iNEV1ZllMaGJRTlZiTzQKxpsHU5r+U7eNTVLoTpo8IL0XPS+D4PBc
            zEut/o/9zxi+sKx2FUIyIJqht98puvqTc3Ff83/ARKakp0Ju9Tnyag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T22:45:05Z"
    mac: ENC[AES256_GCM,data:CGmlQR01VV2h2U/cROaPczxTqMyQp5QshaS4Zag6PZL9myigLMDUNpfqNhJVqdAV+7S2wilzQCJ0Mx460u/XXr9GkX87PvXik3+zuANR2O6hWnqg31lu93kpQwicHryG/Yhp+l686wHD3YZN/FDdsYeMgACQ3U3yiP2GM83yQbQ=,iv:UPQVYYLMy9Jy31vQMNEV7QRKrTj/fOHrWkJBATxcoYs=,tag:P+h6ECDbFcSHKSaGjWTo9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
