apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: monitoring
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
        claimName: uptime-kuma
  containers:
  - name: busybox
    image: busybox:1.37
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: data
      mountPath: /data
    securityContext:
      allowPrivilegeEscalation: true
