---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        # https://bjw-s.github.io/helm-charts/docs/app-template/
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            repository: ghcr.io/bjw-s/calibre-web
            tag: 0.6.21@sha256:9049b3a3e9afa19f189dfac69db0df944d4638247acfed1f69606e4dd8b7e841
            env:
              PGID: "1000"
              PUID: "1000"
              TZ: "${TIMEZONE}"
              CACHE_DIR: /cache

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 5m
                memory: 470M
              limits:
                memory: 470M

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1026, 100] # 1026 - NFS Owner / 100 - NFS Group
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: &port 8083

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "calibre.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      tmp:
        type: emptyDir
      logs:
        type: emptyDir
      config:
        enabled: true
        existingClaim: calibre
      books:
        enabled: true
        existingClaim: books
