apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:IjsRfSIKkSxeuYuUHYWFF6x06p0quZ1aSCm/gk/YEYLeTrF7J6wNQg==,iv:/QYmguG+m15XGJ7TiGNrupjmi11Xxbpd9OGHiG/UHMo=,tag:/mAE3O0XIcWZ7H0OY6FARQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdXp4R0RxcnBSMDBBbmZF
            Z1hMUGQzTWF2QkpyZGNqQ0pKeFN5RlRSU2pzCnZFbkhJVDRybWhKR3pEU2tGSGVr
            YUhCdzB4d3E1OWxRb1RDM0t3WHhaQ3cKLS0tIHEyUkFrdVJpRkxXSTliS09zNGhK
            aFc1dG5qNEFMUHYyMUdwNThNN3J5NzAK/p+/wWyaAdYZAUJLhcQGQWXBxX8z4+lN
            J/+Yr5DYWssa3g6MuNFabGWGe01PeepQHoPyxz9tWAIe7C5CDL/KzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T17:47:26Z"
    mac: ENC[AES256_GCM,data:A2AWrYC4kgaD7q4OjqfUIHQI5IdNb6/UCGiYfA36dimXnFTMzSF4dAcZGNS9svnRvlhF6wiW6Q3aYT0oAiMfzlOTbOOgwfJnIAgQyP5ZtyNDLAdpsne8jFX7m6dniaUy2tsihyytW/M1pMKBlFS451mTT1u/G5H+zLCh6sj7eFw=,iv:Ejs6ZzBhgOFhsZykQXlpwWMUg3YLZqLsBYsuH9KjTTI=,tag:48ZO7oCiLiOSexKRLB1sHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
