apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:rOOyBWDs9HaqxuTzt7ICytVN9DA4H3EpMKG36ZzzkAqx5y0vLYzwxQ==,iv:x+WlXq/34FVblG/PyvlK48bZgqEc1RSFmZdd8OFgQck=,tag:gnt7H62Btm5jpKlb3j+Vsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcGY0UldtVloyaDcxZFlX
            RjlTQ29mbDdIQ09OM25iWE5iWjZlY1lPWGpNCnVuMzN1SmhTMGMzSHJRRWpWVFJu
            K2JLM1Z0RmJnUGEwOFo3Q2tNanphYlEKLS0tIElHS0hMYnkzU2YzZE05cVNYM1RH
            cjdhR1NFVW9qT29JNkJRU2pucCtVQkkKDyxxj82iNHjpe8vLN3hMUe6dI8/n58bs
            Xg378FXtxvE33GHWUSwaHbtJ5MeHM4xMLns9S3RVVD6WpzMbJppQQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T03:46:27Z"
    mac: ENC[AES256_GCM,data:rL6yqowGzbhj8kir6m3pxzUB6oTjWfic97zU2m0LQ0a5Uu42TB7qA6ZEoTI9fUWoK3dgqrloJJ2T9cYWPn9kawuAWz5vWZC+SGngccIUZfvd2tERBwDA9waJGh8rR7iXLaa7XQDvmO5QvunHTISXGqOi4wptibvelmeW0ZutKwk=,iv:WHfq2eNQYmiBQHXuKrn0unFw1upztxLFEP/Trqryll0=,tag:32nLPc07hHWe3xuFb67yGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
