---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://gissilabs.github.io/charts/
      chart: vaultwarden
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: gissilabs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # https://github.com/gissilabs/charts/blob/master/vaultwarden/values.yaml
    # Focus on intel for now.
    nodeSelector:
      kubernetes.io/arch: amd64
    strategy: # Need to turn down then turn up (depend on one persistent volume)
      type: Recreate
    env:
      TZ: "${TIMEZONE}"

    vaultwarden:
      domain: https://vault.${SECRET_DOMAIN}
      allowSignups: false
      showPasswordHint: false
      enableWebsockets: true
      verifySignup: true
      allowInvitation: false
      smtp:
        enabled: true
        host: ${SECRET_SMTP_SERVER}
        from: ${SECRET_SMTP_USERNAME}
        fromName: "Vaultwarden"
        port: ${SECRET_SMTP_PORT}
        user: ${SECRET_SMTP_USERNAME}
        password: ${SECRET_SMTP_PASSWORD}

      yubico:
        enabled: true
        clientId: ${SECRET_VAULTWARDEN_CLIENTID}
        secretKey: ${SECRET_VAULTWARDEN_SECRETKEY}

    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      host: &host "vault.${SECRET_DOMAIN}"
      tls:
        - secretName: vaultwarden-tls
          hosts:
            - *host

    persistence:
      enabled: true
      size: "1Gi"
      existingClaim: vaultwarden
