apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:4FFwFeRSjZMtqB0ajAEJ2DkvkFQhkA27eRR95qrHk82I87yRxmAUXN0BNwTZtNrYiqNMrli0Y0WNq82VwbF6bumqC9euKXRoUsTOOfRfM4B/,iv:x/8G/yMnnvpMkHkbQdD63EESp7DwN9//t9IBYYwTT34=,tag:3gh81EUCASAFmLNt4o1tuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQXZoY2ltdFAzVlJGTmNl
            VzFXMXAxa1BtLzZ0NmxyTnFuUHcyMElmRHpNCmVVQndXRklaelZIdi9OV0kwVVJO
            L094a2FydHlGTVdYckV0SnhLSi92SVEKLS0tIG13bEhwYklBMlpOQlJYb1BRS3hW
            QnVrREJnbG9YWTdpVlpnOTlSL3BBYkkKW0QuvKi9nfaFMln2m241icdezsYL21jd
            SAgbKpsMRLNkxi0gfbmbTjhxIlice1Xq2q32WTFc8PAEWQWq8sqrMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T22:29:23Z"
    mac: ENC[AES256_GCM,data:9JLNzTJ0qsX2yj0hntRGZg1hnFXc2qtceB8MNw2c2fYWcmSOBnEHbB4QJUXA3BKoUDdGeQ0pxL3aDu6N12+BOhL9vN35/rjThzYhYjXfEeyjhH3qnXoO7v/iFD5X6RYH+DNZLr+Th9GZOlT3sMJlPFS55Wp5uXG7q8Dj0XNSBNY=,iv:2PXPegDQ7wveZnK8jNslSiWuUF5Aj+OH5rNwBHTPKBM=,tag:nQQw4cvcVvDTIZ90T4W8OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
