apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:vLSQq5ngZw==,iv:Gi6mhpcLnNRXVu5N8IouJ811vfGp4t/Jmtjuj3o4p1c=,tag:/upza6FKBEAT3vfH7A91HQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:YPsAROLnhb9VdfhnpEk4lUo=,iv:145WFToJi8g9POEeB4Yt4SI2G9VzxgH6l8G0kybM+N0=,tag:Y3I/g26qLdPdCNzYII6ohQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Hz1Fv4G/SC61e0GMPvT9ZgVYKzwCoNWuCQH/cFMWMK+WRbpN,iv:ZKEZbe0PByfJJYHzSEQjvgAYG/vnrT7dfGwxWHf3ivQ=,tag:ohqkBZLepPBznowiVSIhPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcDcrTXpkZERGZUxKMUor
            QzVhbzhOL0hsd0Q1VjlOdWFWaG9Namg2enhZCnJ2ZUpPWnBuT1VlaTQ0NXBqOE5N
            OHdDTGhSNnViMjVaa1QweGpHVzFvM0kKLS0tIEpSTFNQcUM1SmhtWXFzTkZWOHl4
            NzB0QmVMN0hxellZWDcyN05qL3poTmcKFoQGTswYEPyADUKgu33vuvkOf35U0rhG
            QWXXOKaA7Bl7lpaPzzD0rS2eiFvuNeAy2SVVJATYEi+3w6fCzDhGRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T04:01:30Z"
    mac: ENC[AES256_GCM,data:2gRg5hQE05XA8GX2AjpZCweDmKJiIypaMB557TowDtfwqac7zpyMoCp3LlQRp6jwSVS2K8IAQbtf8p3N0DVmlvgHwNSlgvQuGWQfocdhryFQcAWpxVh202udFcr/SMEavMpeNbL3UDsnw6DLEPV+HvQHBCG7aak8neTENh5pVHU=,iv:Axlctbntw0T6LbWsXANlFCjoltUt/zCaBxVNBXyNBiM=,tag:QHRJOrQPxOvsZ3d8lORV3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
