apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:MEBfMM0BpguCfI8=,iv:5iGYBRjQcV7Uz6BPF9aGrptk6spvpt8q3EMk5+OIFHM=,tag:TNSF7Ot7wDMf5+sa8+KccQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Vyf+M9ld4MgRzIFJQ1HNB1M=,iv:5IODkXyw70TlH8SOs57E1zTXc0nM4QgdFDr/QcsD1QA=,tag:S9qqb14+6kU1Jd4D1AAfXg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:mPi8O2yLJwiRKy10qHHYNVsmNCqcmmJ7/Xyeb3WaHMhcWLtm,iv:R3VW1GHH/DuxD9/jV6EC9aVJ1TWfj5RqpGiPmtwclc0=,tag:0PNohVrR2RvMKkI9iro0uQ==,type:str]
    SECRET_VAULTWARDEN_CLIENTID: ENC[AES256_GCM,data:uLuI5qY=,iv:euBfIfxFVMp33DdgkH4tdgehD2syI/kMHIwUx8HWntE=,tag:PKwmBobKnjXbvVgy9viJ5g==,type:str]
    SECRET_VAULTWARDEN_SECRETKEY: ENC[AES256_GCM,data:s8dT+SALdBhLFg3nk2N2ZHdxnOIeJECAvwUB,iv:xPgdmpt9SmIjTrf+ImhQqyziEHG0F8fXpHZnGdyiUkY=,tag:SKxgIfzpLPZLsjNtV0Gktw==,type:str]
    SECRET_STORAGE_ADDRESS: ENC[AES256_GCM,data:YSEd/Pe+shp8Gw==,iv:chcbFaLMz8+bG5EPN0Gkvy93A2Qgv8N+ByyRLfVJ8GQ=,tag:2jWJI7HouJvt+MhfTm5BtA==,type:str]
    SECRET_STORAGE_IQN: ENC[AES256_GCM,data:faD6JDvWAsz//iHQm72uanpOmVZHreHx,iv:v+IIamMLHpJU1Vc1YwkKSgJpPEFS4+Ctn1dAdv2FPCM=,tag:HCddZPm6NCqgHLtgKvuyyQ==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:N3xuLwdELR69xle/MfU=,iv:C5JiGeD9bhWJfsSacT7uRQq1e6QhwawcHIpOUJ/nK/I=,tag:Ff+aY7BRvuWBWzbnDQd+2A==,type:str]
    SECRET_SMTP_PORT: ENC[AES256_GCM,data:muv6,iv:gdXBTCXxRXYgvhWrop++pxmEyCvXmB9BxUA6+yryirk=,tag:NcCywV2NEg5JdN2gyfclBg==,type:str]
    SECRET_SMTP_SERVER: ENC[AES256_GCM,data:GwJtw+0fCQs5QsTwXcY=,iv:pO92jtb+dGrfw4Td2ateFl11Q+5DdsXqKBnCGiWIsQY=,tag:4FFcyz0cCGrAwSXCpdXksg==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:Jw9eoUsV2qZuLRD32Yu4hE0=,iv:qgXGtSn2ryrPu3ZwQZdPecvgzoGkScGqVY5y5HsWrrg=,tag:OJLfCw0Qu6CkQTmf8x2P3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bFB3a01zd3Bqb3ZWVFdB
            S1Rpekd2dU1abENmRktldCt4WUU2ak1sMjE4CjBwS2cxbXo4d2tMQnlZQUpXWGRF
            SG90RlZ2cWM4dlJHMHlISXNYQlhTUjAKLS0tIEFoNDBMUnVDWUhkd09XQnFQMU9U
            L0pyYjdLQjlnVm8rOTV3YmhzSFZmNHcKxtuKhQOyytQf1zJjZN/fXS9fZ/aHOG/F
            7NVWYmEiGxQW0gRHpWiycQKs8VKFRVkqsEgV6Mzzs1yIGOvsrd7MSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-09T00:17:43Z"
    mac: ENC[AES256_GCM,data:a8ckKZnpgDqJiXKbpM1D55gdMeqiLerCUGyZ3XhLIZtTbourjFXXISnnvL1O1/UWO8sAmUtfSd8OILMMUhHP8r/qJjGRtq+CwkjXvQqqdDf7zAFRU5Z8E8G7jYEgYVNPxkMBZqR5CFESiBESVYhKXWEkqzqF27YCagaTehG6SXY=,iv:u3WqsqPsnYEHQfTHZwLiFxD0kA16cgBgjYgkiv58UHc=,tag:fQ8KNX/hYt+q3/z3mkCCHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
