apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:zTUBSrX2FpfXnw==,iv:BHnvnkyAeyQWxjcn1Cz/REGbepKVgehFE+0oH0ejSMQ=,tag:Tp0YVlmB9PAVIGOLAFRQZw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ACoZyvL7ghrWujjvLCwRaqE=,iv:tQ65bs6ICuweVQrFKDNiPsnN9rBzl6gsfGdvrpruHVQ=,tag:DlZciG5nXfj5frkgk7H7Cw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:PpLpBIiDpbaWwsGIfryYR0pTJ9uyf/Zc7yUCzmwFfHC/VnOe,iv:WBuXEQ9f/xcH6fGD7g6cd0YVZcnAVhlmdydAyq07YZM=,tag:klKKrZ6zdMTR/xkfeeiGjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z2JOaW1SYTl3UWpxejZK
            aGUzSXQrYjNpZlpubnliTUxKaTNzeVkxNzJBCmx0VUExMm5WNXhXVHBwamlXTktG
            OHFPcXdtb0tqUWdhOHdWanhsTmNKS0UKLS0tIGtiQzh6STU3cG5OTjVhTU5GMk5G
            WklUalhJKzc2bXh0MGJEaEltRFdqYzQKM1yErUdXBHfLJIBuOniyekeGIZ6h8hdN
            JSycKM2RF3JjHslZjw9kobMlOQeZxY3Gh1diPvqFMDEBWMVh6rFLwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T17:31:35Z"
    mac: ENC[AES256_GCM,data:3z0YyJ2acP/05gstDl/YWt+VhhMusjUGwwehUMe4cMcVVF7ip3T8NC39nXo348jYUHRplUZbWwwPhLaE/vqBFKEuYsZeaxJviyCcUxTk+FKxbNmqV82l6U5FvG+mcuHFWfufazxo1ls2w6l9Dd8IP8xqgf8X9DL1b/wGm8Qlj24=,iv:7HD+uOUNH/tHWgZ1KZH8/Ot9CypDVZVnjxpWFXWEkMU=,tag:zzJj+O/n9mMHB53Y2KdBCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
