apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:CGOpO+pWrYyfrLX3koTp4AS/Eine5/w6JkACsV3yRSs=,iv:gxfDDIznmnQxfWxwpTpVLrsre6jJXMDcbjP5onUwvP0=,tag:pkd9WTxGVDy8NKqS1rehtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UkpVVThVSXlHdC9PVm1Y
            R01aYzhkQmdrd0kyU3Z1bFVCL09CSG5CbVhRCjR4VU9GWFJUWjRaVjZidHhuTTV0
            bDZvTHV6cUpwNTFYdHFHQ0xOTGJ4WWMKLS0tIEhmTVFkTHR6Vk1LMVdpUFBRcjBr
            RVYxOVZ2ZkwzMk5LckRZdm1mZURCMWMKcxbAHLNAtZohFdXHssbZISS6t/FJsR8t
            czHpnqav86TLbVs5gt1nIGvtaDps2uwNnr5kqLuUwytsm881dAwpRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T22:13:37Z"
    mac: ENC[AES256_GCM,data:H6o0gM53rVDML6U0ogEEUrxyUFsw5HMy+azZztd+xZWbip5SROOAXAUTbtZC2fDwZ7k77CKTA4lq0I2SaWrXVZH1EvWDwg+0ioF2KZuYR/q+5BycFRbNUxRwOar2UI699dX8V7QX8kfylWkAn6N4682Dd1GVBZsfQO6C8PgJp4o=,iv:+GXls30U4/7kBj20xFWlNfzzjZMbDBArVjnmpS2TgJk=,tag:QSEpXfjtUlJmN7AZeu7Zsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
