apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:iasI53RHmJNpFa642UBp0MICLb7GP+1QXaYGEXUnUpo=,iv:mvMcPJOlAKT5Z+qh45fZqJWBpTJjGqLdwW1IoRqapx0=,tag:QZ3nUJkVgWzD4XcAvoq/5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaUdvUnlvdk91NGRwY2Nu
            N2hPNkVwQ1E2UzJNeEdOWldYL2JSaDhlNHdzCm9wczdmUExzQ3NvTzdSOThqNlVH
            Y2p5Q3ZKcDJISXQ5dUdwa3U5NHc0TDgKLS0tIC9BR0lzcElwSmFLaEcvWXFVOSt0
            YjlCTTlMdmVzeFgvNkViWEZHeHVtWmsKygOYKYK0LE4e10zh6UJRZ34/+1PX97c0
            CZ7L743XzkBYxt1pP7VaaTVHq7tEev3UtuHIlPmv7MNvAr9kNNr07Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T17:09:15Z"
    mac: ENC[AES256_GCM,data:/OjNIeySd4TDEXiVcz0BOAwGoTy5pv7k6ncSGTm04kMpNS44Wz4E/mZcTCUhGjOSlJt9Nvc8pSDX4wdvxCzA/618IllsSxmiK5kwWADXVJSx3Id0tPVvOCTY21Hj0dzKNC2MMRNuCmkFZhml+Ev7Uv/RH1yl/yO4Ac6HznyC1Hw=,iv:buTWwCwQHOeVA3JJYFPeCL56l7DOki8/1jTe6joLH2Q=,tag:QulnPfkqDnWAc36iGtc49Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
