apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Y1eSOlMSQxLlv+KywJJxOGi3IMOEgqSXD9qL0CI79PQ=,iv:kEGwpIa3M0/dQLEb1Ry2kRwqM1Qwbw+wEft0TLdIaE4=,tag:cLeYK/siKnLwJ98ZqLQZyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWkF3M1ZNalRyNm04a3ZG
            OU1qOEE2R1loUmdaNlVSOFh0N0hBazVobmdvCkFHWS9sK2NHUGlKakIxU1RrMU91
            VkFPTUpydklyVmEyS2FwR2N3Wnlya0UKLS0tIDUyZWt0cXhMQ3JuM2pjVzBVV2Zh
            ckFYckJ1dnY3SEZsb0twaWlqTGZIa2sKhGBf8zCLHDr4lrM+UV1bnws5wiY0EQ2q
            szqWFyW4xrTbKoecWdsIWSRGV5CvUC9R2V3b/+L05Hk6RClgkkV2uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T17:47:26Z"
    mac: ENC[AES256_GCM,data:KO6aSgJ1REqzhkxMzOCJMi6cyv0J2/pt8SI1nfeb54PCeuWcuffzyehQyiTebpXYITdPpdg4SThRbjWcK3FAVmILrvGPcaQv+wqAs/ld0INwtNICWyD1J9QIpYSadXuBPgfiO5kKtb8VEGEoRCNIuCef8DRektMkJHlRTm7eLDE=,iv:BnttgG/iETFaq1k5lldfg0eGcAe0C+qk/1XHNxXM3UA=,tag:68ccCc6jZnET8pAausee8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
