apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:4WZdfVTIYP3HGhJA7p/Mwcf9alfQmaRMpm9r8g5UVb4=,iv:pdyUoKX04X54RgdsDTs8FGfxOSmJzdgAnIHJgV/JG4E=,tag:Yygo45Hz3L1Po8VWW9H3CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNFlhNjR4dUNWN3NCeE1v
            dmNDaEV1OW5hWEtlQVFMSnJlY204MFpld2lRCmxDVzMrZ2VhRTE0NitaWmpyakFD
            VjI5SXJrd1NvM1BDaGNINjRpR2ZFbGMKLS0tIDJHK0daNnpocXA4bVRoMm85clMx
            RnNmYlRWeFI4M1dZcEp2NGZxNEJqZ2sKCawJfpvsPxrrad4tps2W1Lt14wIpvwFE
            W6a7OADlQp9Zy6epDt7vm8NP/Y1TPFKulyDahrqmaOPBKDDApL/ThQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T22:26:58Z"
    mac: ENC[AES256_GCM,data:RmkdoECIf0fEpEsr6L04xLGjpBc3vpQi0JBhJO8tbzVUel9ldlva59GQlg2nKke+fcmIBISxjKLA2UV/5BcB161MVJ/6yd9jpHjhpm4eJdg3Dg1Zqvp+BZkbwclxBtJJwUvudRFmUHsIEnuwucApeMWXnW2iCzZveGWJDWd6G5w=,iv:u/nFDDtAYoKtkvxyXqbs0NOyX2H8J5EEBCffGXjN3Js=,tag:VDnDajoaZ3V0RcfY7n2yCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
