apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:9heg4I2rS82bj5NYsTe29N49S1YZA5Q4FFVKauKOz3eo+J5/8x3ZJw==,iv:1RMsEbTzc+GkYl5yeMS1UoEfwspZ0VvrqBmMsUj46Ek=,tag:3eAxfinrD+EmZGfu+hMftA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQ1ZFeWFhUkN5bVBjV2pu
            WGw1eHRyMnk4VHlvcXRFcXFQS2xJOVN1U2tVCkR3ZGRiNllidmZobWJBQnJ2b1FF
            ZDJUNGY5QjljbG9ndGcvbXFHUWVpZzQKLS0tIEVobkU0cnFkUWttZVY3NDVtWkFz
            REpiUHRjbjI3bzJLR2F4cDNuRVlGRWsKvqX5NBuIs9DJmvgc7KfvZfJDC5oZMm73
            Vc4d4vjWqr43YH6qSNDih82ilzHCMEpMJeMNHgGVjgK/n3amNSmzZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T04:20:20Z"
    mac: ENC[AES256_GCM,data:TWFcqOhoQv0SwGyt9ruW6TWy4K+N0zuKTs9K3YAZ+oWI/SAKX7Inag9MXTfuOoV6X9eSjvm5VQttV8d+gTgooNakHpWoP0RAcoJGv+g/ZkXTfRsN52C8iBEkXvEbHZyW0dGve1UJ5+1aXHZpcfhhvNeeI+OCSuYFa92XhwgNd8M=,iv:VX+t/pIhVMRI2dnJJRcB1DbShsEC7x+tM9npTIiuwKQ=,tag:SQ/hwETQGSim1S9NWPEbmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
