apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:grsmJ4WIb34hhMu+bbdWg0UjleXwGz0+bmnFCsJhbC9KRHTwMa5Jpw==,iv:G8N63vHBOdu+jzKlWNvkJo49MlohJQw02WgxlwkjdTA=,tag:VfK3XZhdC3wV7gFzKnWd9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU1YrWVBKUE01NEU5STBP
            VzRsdVlDNVMwWVVBcmNqUWdidzVpbGJhdUJJCkZjeEpUU1JFUVRheVJmNnpGVnRI
            RGdwN1IrTEZyMk94aEJSeTlBNitQSDAKLS0tIHVRRGJwdFowYkZCOEUraDBWSmpN
            OGJjL1ZibnVJK0tySVRXQmhKbkpNdTgKLUUUHCB0+2+LQD++cUZqETZLGn87ulWT
            qGnTiGvxvbYpSsGKjW9IM7w7HEkP4QNEPWPzwsFGBddOhYI+g9sHgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T02:33:48Z"
    mac: ENC[AES256_GCM,data:rcPqrzL3DXNgz6U2lugFmveh7/RHIEP7UUHb/VI2zB00Mu83s2tfEGNqNY6elVzEJikGbFnWy1szNYyHUQShkAa5O1Y7KGFwUNdGQjVNrjwfTyeR7y36rSXXOHGZkzRsvSBtM8hNAdS+T0zC2KCLkxC1Xty9jjN0VYBIS+Z6Z0A=,iv:66QvWRKKWi2w3anaA6nmfeRpuELLaDw910BMiYoxwdg=,tag:PSeXAY11hhRmYvWs8mLUHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
