apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:vAv10Okun1dNVjjESL6mU/eiLImOSmbSLE4FDOfHn4wUIE2GyIqWyg==,iv:zjxKx6Td4r2ezTSgPhYvbRtImjCcbxpeKPeRovPxzWA=,tag:/+1kImqd3LryDIkirhBT9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc2dIVDhraEZVL0ZOZEZz
            R21UbEZRM1VJcUZrV1pFcGVtS2RuNXhiZWxzClZFaFBDNG1qUVczblREZ3N6Y0sv
            QlJ2aCswNVBGNWd3Z1YrdU85elN1LzAKLS0tIEF0UGxEMktSOXZMOEFBdjJzL0s4
            bXRyUXY2OFRVeVdTSGhMNlZCNFA0blUKY0sdtW7i1sCOIBL0a5JUUNTxy+Wb2ysW
            dmIZ5GaeNE83QvJWjfA6U8uF0miPg9u2X0m+rXgK6mcpbTrdi+lNnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T22:13:37Z"
    mac: ENC[AES256_GCM,data:Hvbjr28Til8LrgNHS06rWx5E+7e14OYNVRKrfj/14UgnasMhR08vOxQuGTFPc2egCP/NY1zkWdU/YI7M0LKhquW/745XqvSvKUcnb3tr1G5fK+qlAbq20p3rzpHoWvWIPiyT4NSallB4r/dRwZeERsVl+tlOnJjN8woB4LD4zQE=,iv:v73L2HEn3GfNV+5O8t2LO9ufhc8JvkloLzCQQ2iJl6I=,tag:KljP1eRKgLbySKlOppq+mA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
