apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:+pvl64mtF1TORZYRmu8POhEZHr/UYQpEIzk8UyQBwZWS3/HX7SU15Q==,iv:vldq5eJgUw+aDGCEfDAj1kCgc4kA+N1LwH8wu+JCG1c=,tag:i7Eyc9oeB/IVKxqysGroag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpdz9mmsyk7k2zml66wpfxe7cucvjan2js6jrl28hkkr6uj4ju0qvt32x6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVFVkNnkrcTNNYTUyN0JI
            WW12ellzcHNjYXNEVUl4UytYVVVsOXNFeldFCjJpY2p3cHduQ2IySFhhRHJrbC9h
            LzN0Nlp2NnlUbGo4QkxHalJMeitkSFEKLS0tIDhQbkIydTdkdWE2M2d2SzRqYndh
            LzdzK0Rmc0ZWd0E3T1hlMUhML1FHOGcK+eic8Qb0E+g28CR2JDDv4/ybn2nlVMgl
            GSV/iUvjQvoHoy/EQdrwpLGWLjv1TYtEK5i0x65S2rcpCDdajc8PXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-09T00:21:51Z"
    mac: ENC[AES256_GCM,data:t+Pz4j0Ad+wbhxVhTZ8M0PEqkn3WpDofSKE7EERlazseobD6WeIhTZD7Qir7G/XWQZX2LvHvhBVMOe7cnssvXwKaFzjDEkpXD46Qnsw9h3eTw/mbHSPFEEWjO4HSoZxKs7hnK14xxuxKxD9yQtYjzYWP/p0wM1Im5y2P8BM9m1A=,iv:CDiOldemFKXru8SZGgm2NoOXQDkcS85NQIl4PhZ2Z6U=,tag:KWfRvIi+8y9HPoIDbCwbMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
